# permissions for end users to view gstconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gstconfig-viewer-role
rules:
- apiGroups:
  - clusterops.mmlt.nl
  resources:
  - gstconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - clusterops.mmlt.nl
  resources:
  - gstconfigs/status
  verbs:
  - get
